apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/part-of: {{ .Chart.Name }}
        app.kubernetes.io/component: web
    spec:
      serviceAccountName: {{ .Values.serviceAccountName | default "default" }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: web
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NVIDIA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: nvidiaAPIKey
            - name: H2OGPTE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: h2ogpteAPIKey
            - name: H2OGPTE_URL
              value: {{ .Values.h2ogpte.url | quote }}
            - name: H2OGPTE_MODEL
              value: {{ .Values.h2ogpte.model | quote }}
            - name: APP_NVIDIA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: nvidiaAPIKey
            - name: APP_H2OGPTE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: h2ogpteAPIKey
            - name: APP_H2OGPTE_URL
              value: {{ .Values.h2ogpte.url | quote }}
            - name: APP_H2OGPTE_MODEL
              value: {{ .Values.h2ogpte.model | quote }}
            {{- if .Values.redis.enabled }}
            - name: REDIS_ENABLED
              value: "true"
            {{- end }}
            {{- if .Values.nimllm.enabled }}
            - name: NIM_LLM_BASE_URL
              value: "http://{{ .Release.Name }}-nimllm:{{ .Values.nimllm.service.openaiPort }}/v1"
            {{- end }}
          {{- with .Values.extraEnv }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8000
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.redis.enabled }}
        - name: redis
          image: "{{ .Values.redis.image.registry | default "docker.io" }}/{{ .Values.redis.image.repository | default "redis" }}:{{ .Values.redis.image.tag | default "8.2.1" }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: redis
              containerPort: 6379
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
        {{- end }}
