{{- if .Values.notebook.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-notebook
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/component: notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/component: notebook
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/part-of: {{ .Chart.Name }}
        app.kubernetes.io/component: notebook
    spec:
      serviceAccountName: {{ .Values.serviceAccountName | default "default" }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: notebook
          image: "{{ .Values.notebook.image.registry }}/{{ .Values.notebook.image.repository }}:{{ .Values.notebook.image.tag }}"
          imagePullPolicy: {{ .Values.notebook.image.pullPolicy }}
          command: ["start-notebook.py"]
          {{- $token := include "h2oai-floodintelligence.jupyterToken" . }}
          args:
            - "--ServerApp.base_url=/jupyter"
            {{- if eq $token "" }}
            - "--IdentityProvider.token=''"
            {{- end }}
            {{- if .Values.notebook.allowPasswordChange }}
            - "--ServerApp.allow_password_change=True"
            {{- else }}
            - "--ServerApp.allow_password_change=False"
            {{- end }}
          env:
            {{- if $token }}
            - name: JUPYTER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: jupyterToken
            {{- end }}
            - name: API_SERVER_URL
              value: "http://{{ .Release.Name }}-web"
            - name: NVIDIA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: nvidiaAPIKey
            - name: H2OGPTE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: h2ogpteAPIKey
            - name: H2OGPTE_URL
              value: {{ .Values.h2ogpte.url | quote }}
            - name: H2OGPTE_MODEL
              value: {{ .Values.h2ogpte.model | quote }}
            - name: APP_NVIDIA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: nvidiaAPIKey
            - name: APP_H2OGPTE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: h2ogpteAPIKey
            - name: APP_H2OGPTE_URL
              value: {{ .Values.h2ogpte.url | quote }}
            - name: APP_H2OGPTE_MODEL
              value: {{ .Values.h2ogpte.model | quote }}
            {{- if .Values.redis.enabled }}
            - name: REDIS_ENABLED
              value: "true"
            {{- end }}
            {{- if .Values.nimllm.enabled }}
            - name: NIM_LLM_BASE_URL
              value: "http://{{ .Release.Name }}-nimllm:{{ .Values.nimllm.service.openaiPort }}/v1"
            {{- end }}
          {{- with .Values.extraEnv }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: jupyter
              containerPort: 8888
          readinessProbe:
            httpGet:
              path: /jupyter
              port: jupyter
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /jupyter
              port: jupyter
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            {{- toYaml .Values.notebook.resources | nindent 12 }}
{{- end }}
