services:
  # Main web application (FastAPI + MCP server + RQ worker)
  web:
    image: ${WEB_IMAGE_REGISTRY:-h2oairelease}/${WEB_IMAGE_REPOSITORY:-h2oai-floodintelligence-app}:${WEB_IMAGE_TAG:-v1.2.0}
    container_name: flood-intelligence-web
    restart: unless-stopped
    ports:
      - "0.0.0.0:${WEB_PORT:-8000}:8000"
    networks:
      - flood-intelligence-network
    depends_on:
      redis:
        condition: service_healthy
    environment:
      # NVIDIA API Configuration
      - NVIDIA_API_KEY=${NVIDIA_API_KEY:?NVIDIA_API_KEY is required}
      - APP_NVIDIA_API_KEY=${NVIDIA_API_KEY}

      # H2OGPTE Configuration
      - H2OGPTE_URL=${H2OGPTE_URL:-https://h2ogpte.cloud-dev.h2o.dev}
      - H2OGPTE_MODEL=${H2OGPTE_MODEL:-claude-sonnet-4-20250514}
      - H2OGPTE_API_KEY=${H2OGPTE_API_KEY:?H2OGPTE_API_KEY is required}
      - APP_H2OGPTE_URL=${H2OGPTE_URL:-https://h2ogpte.cloud-dev.h2o.dev}
      - APP_H2OGPTE_MODEL=${H2OGPTE_MODEL:-claude-sonnet-4-20250514}
      - APP_H2OGPTE_API_KEY=${H2OGPTE_API_KEY}

      # Redis Configuration
      - REDIS_ENABLED=${REDIS_ENABLED:-true}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://redis:6379

      # NIM LLM Configuration (when enabled via docker-compose.nimllm.yml)
      - NIM_LLM_BASE_URL=${NIM_LLM_BASE_URL:-}

      # Application Configuration
      - PORT=8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  # Redis for task queue and caching
  redis:
    image: ${REDIS_IMAGE_REGISTRY:-docker.io}/${REDIS_IMAGE_REPOSITORY:-redis}:${REDIS_IMAGE_TAG:-8.2.1}
    container_name: flood-intelligence-redis
    restart: unless-stopped
    networks:
      - flood-intelligence-network
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

volumes:
  redis-data:
    name: flood-intelligence-redis-data

networks:
  flood-intelligence-network:
    name: flood-intelligence-network
